### PR TITLE
Create binary_search.c

### PR DESCRIPTION
**Pull request by ragupathi09**
binary search in c

### CODE REVIEW

**Review by ndrohith09 — DISMISSED** [review]

**Comment by ragupathi09** [comment]
> binary search in c

Hi Rohit can you remove the spam label its very helpful to my other contribution try to help me

**Comment by ndrohith09** [comment]
@ragupathi09 What kind of act is this. Cant you wait till I see the message . You raised some sort of spam PR and if i mark it as spam you struggle . You mailed me right . Why can't you wait till I see your mail .

**Comment by ndrohith09** [comment]
@ragupathi09 Very inappropriate behaviour.

**Comment by ragupathi09** [comment]
Hi sorry for that okay .

**Pull request closed without merging**
