### PR TITLE
updated

### PR DESCRIPTION
**Pull request by tanmay002**

### CODE REVIEW

**Review by ndrohith09 — CHANGES_REQUESTED** [review]
Remove all white spaces at bottom.

**Comment by ndrohith09** [comment]
@tanmay002 mention the Issues which you are solving here . Looks like some other has already made a PR in python.

**Comment by ndrohith09** [comment]
@tanmay002 the PR will be closed if it is idle .

**Review by mukesh663 — APPROVED** [review]

**Comment by mukesh663** [comment]
Nice work @tanmay002

**Pull request merged**
